# -*- coding: utf-8 -*-
"""Forbes 2023 Leading Sectors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLye531GDTuTC0sBGfwYThHPSFFCk_xy
"""

import requests
from bs4 import BeautifulSoup

url = 'https://en.wikipedia.org/wiki/Fortune_Global_500'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')
print(soup)

soup.find_all('table')[3]

table = soup.find_all('table')[3]

sector_titles = table.find_all('th')

sector_table_title = [title.text.strip() for title in sector_titles]
print(sector_table_title)

import pandas as pd

df = pd.DataFrame(columns = sector_table_title)

column_data = table.find_all('tr')

for row in column_data[1:]:
    row_data = row.find_all('td')
    idv_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = idv_row_data

df

df.to_csv(r'C:\Users\theda\OneDrive\Documents\Data Skills Bootcamp\Project\Sector.csv', index = False)



